### ISSUE TITLE
Is there a possibility to enable always in command mode?

### ISSUE THREAD

**Issue by krzkrzkrz** [sublimehq/Vintage#73] opened 2012-02-25 11:58 UTC
Is it possible to enable "always in command mode"? For example. When I am switching through tabs. If Tab 1 and 2 are in INSERT mode. If I am in Tab 1 and click on tab 2. Tab 2 automatically switches mode to COMMAND mode. 

Similarly, if I click back on Tab 1, it switches automatically to COMMAND mode as well.

**Comment by misfo** [comment] 2012-03-09 05:35
This is a duplicate of #45

**Closed as completed by misfo** 2012-03-09 05:35 UTC

**Comment by andersonfreitas** [comment] 2012-08-25 15:18
This is not the default in Vim. I had these lines in my .vimrc in order to get MacVim to behave this way on FocusLost:

``` vim
" Return to normal mode on FocustLost
au FocusLost * call feedkeys("\<C-\>\<C-n>")
```

As a long time vim user, I really missed this behavior in ST2+Vintage (just like you) so I coded a small plugin to always return to command mode after switching tabs or windows:

``` python
import sublime, sublime_plugin

class ReturnToVintageCommandModeListener(sublime_plugin.EventListener):
  def on_activated(self, view):
    if view.settings().get("is_widget") is None:
      view.run_command('exit_insert_mode')
```

This solves your problem. :smile:

Maybe somebody could merge this in Vintage adding an option like that?

**EDIT:** The snippet code has been updated in order to ignore widget windows (https://gist.github.com/3818550)

**Comment by jordwalke** [comment] 2012-10-02 05:38
@andersonfreitas: That's a great plugin. I think a better default behavior would be to only exit insert mode when switching focus to a different file within a single sublime window. That way you could quickly CMD+Tab to a different program like a web browser to quickly reference something as you're typing without leaving insert mode.  However, I don't see anything of the sort in the current version of the vintage API documentation: http://www.sublimetext.com/docs/2/api_reference.html

**Comment by jordwalke** [comment] 2012-10-02 07:47
@andersonfreitas: Also - did you notice that the plugin you created causes the CMD+t window to start in normal mode - that's surely not what we'd want here. Do you know a way to avoid it in that case only?

**Comment by andersonfreitas** [comment] 2012-10-02 12:19
@jordow Yeah, I've noticed it right after posting this snippet here. There's a slightly modified version that works properly with `⌘+t`: https://gist.github.com/3818550

**Comment by jordwalke** [comment] 2012-10-03 05:02
@andersonfreitas: That's working well. That would be great as an addition to Vintage (configurable, of course) or a standalone plugin installable through PackageControl.
I'll let you know if I see any issues with it.
