### ISSUE TITLE
pasting yanked lines at end of file does not insert new lines properly

### ISSUE THREAD

**Issue by sheam** [sublimehq/Vintage#133] opened 2012-06-13 14:59 UTC
Consider

```
line one
line two
```

Put the cursor on line 1, then ddp should put line 1 below line 2. Instead it yeilds this:

```
 line twoline one
```

**Comment by misfo** [comment] 2012-06-13 15:02
Dupe of #100

**Closed as completed by misfo** 2012-06-13 15:02 UTC
