### ISSUE TITLE
Some text objects don't work inside of strings

### ISSUE THREAD

**Issue by ghost** [sublimehq/Vintage#75] opened 2012-03-04 18:14 UTC
When the current file's syntax is set to a language that contains strings, the `[`, `(`, and `{` text objects don't work inside of them.

Specifically, when inside of a string (or a regex pattern), those text objects only act on a single character. When using visual text objects like `vi(`, the character _under_ the cursor will be selected; when using normal text objects like `di(` or `ca(`, the character _before_ the cursor will be deleted.

Interestingly, the `"` and `'` text objects still work when nested inside of strings.

This isn't directly related to the issue, but where is the method `has_non_empty_selection_region` documented? I've checked [the API](http://www.sublimetext.com/docs/2/api_reference.html), and I don't see anything there. A Google search for ["def has_non_empty_selection_region"](https://www.google.com/#hl=en&output=search&sclient=psy-ab&q=%22def+has_non_empty_selection_region%22) returns only [this](https://gist.github.com/1109445). It is used extensively by this plugin, and the code path for the above-mentioned text objects calls it.

**Comment by misfo** [comment] 2012-03-09 05:41
Can you post a specific chuck of text in a specific language that will reproduce this issue? I can't reproduce this...

**Comment by ghost** [comment] 2012-03-09 17:34
Sure! Open up a new file, and paste the following:

```
"This text has (parentheses) and [brackets] and {braces}".
```

Then, set the syntax to JavaScript (or C#, or CoffeeScript, or C++, or any other language with strings). Position your cursor in between the `( )` then type `di(`, or `va(`, or `ci(`, etc.

If you used a visual text object, only the character _under_ the cursor will be selected. If you used a non-visual text object, only the character _before_ the cursor will be deleted. The same thing happens with `[ ]` and `{ }`.

In Vim, those text objects would work as expected, even though they are inside of a string.

**Note**: I accidentally hit the "close" button.

**Comment by misfo** [comment] 2012-03-10 05:11
Ah, I see what you're saying. I just assumed that Vim ignored brackets within strings, but it doesn't. Since Sublime's `expand_selection` command that is used for these bracket-matching text objects ignores brackets within strings, this would take some wheel-reinventing to implement.  It looks like Vim ignores the brackets if they're unmatched, so that would have to be included as well...

**Comment by misfo** [comment] 2012-04-05 15:11
I just ran into a case where this would have been useful (editing giant strings of SQL... gross).

I created [an feature request in UserEcho](http://sublimetext.userecho.com/topic/104713-/) for this feature. Since there really shouldn't be any Vintage-specific code for this (i.e. if the features implemented in Sublime it should Just Work in Vintage mode), I'm gonna close this issue.

**Closed as completed by misfo** 2012-04-05 15:11 UTC
Labels: confirmed
